# Generated by Django 5.0.6 on 2026-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('science', 'Science'), ('technology', 'Technology'), ('engineering', 'Engineering'), ('math', 'Math'), ('cross', 'Cross-Cutting')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('stem_challenge', 'STEM Challenge'), ('guided_research', 'Guided Research'), ('project_starter', 'Project Starter')], max_length=20)),
                ('description', models.TextField()),
                ('grade_level', models.CharField(choices=[('K-2', 'K–2'), ('3-5', '3–5'), ('6-8', '6–8'), ('9-12', '9–12')], max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Estimated time in minutes')),
                ('materials', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concepts', models.ManyToManyField(blank=True, related_name='activities', to='core.concept')),
                ('standards', models.ManyToManyField(blank=True, related_name='activities', to='core.standard')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['title'],
            },
        ),
    ]
