# Generated by Django 5.0.6 on 2026-06-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='subject',
        ),
        migrations.AlterField(
            model_name='activity',
            name='grade_level',
            field=models.CharField(choices=[('3-5', '3–5'), ('6-8', '6–8'), ('9-12', '9–12')], max_length=10),
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(choices=[('3-5', '3–5'), ('6-8', '6–8'), ('9-12', '9–12')], max_length=10)),
                ('subject', models.CharField(choices=[('science', 'Science'), ('technology', 'Technology'), ('engineering', 'Engineering'), ('math', 'Math'), ('cross', 'Cross-Cutting')], max_length=20)),
            ],
            options={
                'ordering': ['grade_level', 'subject', 'name'],
                'unique_together': {('name', 'grade_level')},
            },
        ),
        migrations.AddField(
            model_name='standard',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards', to='core.strand'),
        ),
    ]
