# Generated by Django 5.0.6 on 2026-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_standard_subject_alter_activity_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['grade_level', 'strand__name', 'code']},
        ),
        migrations.AlterModelOptions(
            name='strand',
            options={'ordering': ['subject', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='strand',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='standard',
            name='grade_level',
            field=models.CharField(choices=[('3-5', '3–5'), ('6-8', '6–8'), ('9-12', '9–12')], default='3-5', max_length=10),
        ),
        migrations.AlterField(
            model_name='strand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='strand',
            name='grade_level',
        ),
    ]
