# Generated by Django 5.0.6 on 2026-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_standard_options_alter_strand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='grade_level',
            field=models.CharField(choices=[('3-5', '3–5'), ('6-8', '6–8'), ('9-12', '9–12')], max_length=10),
        ),
    ]
