# Generated by Django 5.0.6 on 2026-06-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_standard_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='grade_level',
            field=models.CharField(choices=[('3-5', '3–5'), ('6-8', '6–8'), ('biology', 'Biology'), ('physical_science', 'Physical Science'), ('chemistry', 'Chemistry'), ('earth_env', 'Earth and Environmental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='standard',
            name='grade_level',
            field=models.CharField(choices=[('3-5', '3–5'), ('6-8', '6–8'), ('biology', 'Biology'), ('physical_science', 'Physical Science'), ('chemistry', 'Chemistry'), ('earth_env', 'Earth and Environmental')], max_length=20),
        ),
    ]
