# Generated by Django 5.0.6 on 2026-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_activity_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instructions_pdf',
            field=models.FileField(blank=True, null=True, upload_to='activity_pdfs/'),
        ),
    ]
