# Generated by Django 5.0.6 on 2026-06-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classroom_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
