# Generated by Django 5.0.6 on 2026-06-16 20:51

from django.db import migrations, models


DEFAULT_GRADES = [
    (1, '5th Grade'),
    (2, '6th Grade'),
    (3, '7th Grade'),
    (4, '8th Grade'),
    (5, 'Biology'),
    (6, 'Physical Science'),
    (7, 'Chemistry'),
    (8, 'Earth and Environmental'),
]


def seed_grade_levels(apps, schema_editor):
    GradeLevel = apps.get_model('core', 'GradeLevel')
    for order, name in DEFAULT_GRADES:
        GradeLevel.objects.get_or_create(name=name, defaults={'order': order})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_activity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='activity',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, related_name='activities', to='core.gradelevel'),
        ),
        migrations.RunPython(seed_grade_levels, migrations.RunPython.noop),
    ]
