# Generated by Django 5.0.6 on 2026-06-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_activityprompt_prompt_type_studentresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprompt',
            name='response_type',
            field=models.CharField(choices=[('text', 'Text Response'), ('video', 'Video Response')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='response_video',
            field=models.FileField(blank=True, null=True, upload_to='student_videos/'),
        ),
    ]
