# Generated by Django 5.0.6 on 2026-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_activityprompt_response_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprompt',
            name='table_headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='response_table',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityprompt',
            name='response_type',
            field=models.CharField(choices=[('text', 'Text Response'), ('video', 'Video Response'), ('table', 'Data Table')], default='text', max_length=10),
        ),
    ]
