# Generated by Django 5.0.6 on 2026-06-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activityprompt_table_headers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.activitysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
