# Generated by Django 5.0.6 on 2026-06-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sectionlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityprompt',
            name='prompt_type',
            field=models.CharField(choices=[('student', 'Student Prompt'), ('instruction', 'Student Instructions'), ('teacher', 'Teacher Note')], default='student', max_length=15),
        ),
    ]
