# Generated by Django 5.0.6 on 2026-06-25 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_activityprompt_prompt_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='assigned_modules',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='core.module'),
        ),
        migrations.CreateModel(
            name='ModuleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activities', to='core.activity')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activities', to='core.module')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'activity')},
            },
        ),
    ]
