# Generated by Django 5.0.6 on 2026-07-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_module_classroom_assigned_modules_moduleactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_handouts/')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handout_files', to='core.activity')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
