# Generated by Django 5.0.6 on 2026-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_activityfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
