# Generated by Django 5.0.6 on 2026-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_activityfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_teach_stem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teach_stem_approved',
            field=models.BooleanField(default=False),
        ),
    ]
