# Generated by Django 5.1.4 on 2026-07-17 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_activityprompt_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='If true, hidden from library; only visible to assigned Teach STEM teachers.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='restricted_teachers',
            field=models.ManyToManyField(blank=True, help_text='Teach STEM teachers who can access this restricted activity.', related_name='restricted_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityprompt',
            name='prompt_type',
            field=models.CharField(choices=[('student', 'Student Prompt'), ('instruction', 'Student Instructions'), ('teacher', 'Teacher Note'), ('video_embed', 'Video Embed')], default='student', max_length=15),
        ),
        migrations.AlterField(
            model_name='activityprompt',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TeacherSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
