# Generated by Django 5.1.4 on 2026-07-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_projectstarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_activity',
            field=models.ForeignKey(blank=True, help_text='If this activity was copied from another one, points to the original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='core.activity'),
        ),
    ]
