# Generated by Django 5.1.4 on 2026-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_activity_source_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttopicsubmission',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projecttopicsubmission',
            name='overview',
            field=models.TextField(blank=True, help_text='Project goal/overview.'),
        ),
    ]
