# Generated by Django 5.1.4 on 2026-08-11 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_projecttopicsubmission_materials_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProjectReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Which STEM project did you implement?', max_length=255)),
                ('success_rating', models.CharField(blank=True, choices=[('very_successful', 'Very Successful'), ('successful', 'Successful'), ('somewhat_successful', 'Somewhat Successful'), ('not_very_successful', 'Not Very Successful'), ('unsuccessful', 'Unsuccessful')], max_length=30)),
                ('engagement', models.CharField(blank=True, choices=[('highly_engaged', 'Highly engaged throughout'), ('mostly_engaged', 'Mostly engaged'), ('mixed', 'Mixed engagement'), ('mostly_disengaged', 'Mostly disengaged'), ('not_engaged', 'Not engaged')], max_length=30)),
                ('evidence_of_learning', models.TextField(blank=True, help_text='Evidence that students met the learning goals.')),
                ('improvements', models.TextField(blank=True, help_text='What would you change or improve next time?')),
                ('future_plans', models.JSONField(blank=True, default=list)),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('student_work', 'Student Work Example'), ('supporting_material', 'Supporting Material')], max_length=25)),
                ('file', models.FileField(upload_to='project_reflections/')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.teacherprojectreflection')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='LessonFeedback',
        ),
    ]
