# Generated by Django 5.1.4 on 2026-08-11 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_teacherprojectreflection_reflectionfile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReflectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_reflections', to='core.activity')),
                ('classrooms', models.ManyToManyField(blank=True, related_name='student_reflections', to='core.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reflection_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReflectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjoyment', models.CharField(blank=True, choices=[('loved_it', 'Loved it'), ('liked_it', 'Liked it'), ('it_was_okay', 'It was okay'), ('didnt_like_it_much', "Didn't like it much"), ('didnt_enjoy_it', "Didn't enjoy it")], max_length=25)),
                ('challenge_level', models.CharField(blank=True, choices=[('much_too_easy', 'Much too easy'), ('a_little_too_easy', 'A little too easy'), ('just_right', 'Just right'), ('a_little_too_difficult', 'A little too difficult'), ('much_too_difficult', 'Much too difficult')], max_length=25)),
                ('enjoyed_parts', models.JSONField(blank=True, default=list, help_text='Which parts of the project did you enjoy most?')),
                ('learned_something_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('skills_improved', models.JSONField(blank=True, default=list, help_text='This project helped me improve my...')),
                ('one_thing_learned', models.TextField(blank=True)),
                ('most_enjoyable_part', models.TextField(blank=True)),
                ('biggest_challenge', models.TextField(blank=True)),
                ('change_one_thing', models.TextField(blank=True)),
                ('want_more_stem_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('real_world_connection_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.studentreflectionassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reflection_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
