# Generated by Django 5.1.4 on 2026-09-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_topicsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_program_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='program_staff_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('subject_taught', models.CharField(blank=True, max_length=200)),
                ('num_students', models.PositiveIntegerField(blank=True, null=True)),
                ('years_teaching', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProjectReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Which project did you implement?', max_length=255)),
                ('success_rating', models.CharField(blank=True, choices=[('very_successful', 'Very Successful'), ('successful', 'Successful'), ('somewhat_successful', 'Somewhat Successful'), ('not_very_successful', 'Not Very Successful'), ('unsuccessful', 'Unsuccessful')], max_length=30)),
                ('engagement', models.CharField(blank=True, choices=[('highly_engaged', 'Highly engaged throughout'), ('mostly_engaged', 'Mostly engaged'), ('mixed', 'Mixed engagement'), ('mostly_disengaged', 'Mostly disengaged'), ('not_engaged', 'Not engaged')], max_length=30)),
                ('evidence_of_learning', models.TextField(blank=True, help_text='Evidence that students met the learning goals.')),
                ('improvements', models.TextField(blank=True, help_text='What would you change or improve next time?')),
                ('future_plans', models.JSONField(blank=True, default=list)),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_project_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProjectStarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('competencies', models.JSONField(blank=True, default=list, help_text='[{"skill": "", "description": ""}]')),
                ('steps', models.JSONField(blank=True, default=list, help_text='[{"heading": "", "items": [""]}]')),
                ('tips', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('admin_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_project_starters', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_project_starters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProjectTopicSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True, help_text='Project goal/overview.')),
                ('classroom_name', models.CharField(blank=True, max_length=200)),
                ('grade_level', models.CharField(blank=True, max_length=100)),
                ('num_students', models.CharField(blank=True, max_length=50)),
                ('standards', models.TextField(blank=True)),
                ('background_concepts', models.TextField(blank=True)),
                ('research_questions', models.JSONField(blank=True, default=list)),
                ('materials', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('admin_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_project_topics', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_project_topic_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffReflectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('student_work', 'Student Work Example'), ('supporting_material', 'Supporting Material')], max_length=25)),
                ('file', models.FileField(upload_to='staff_project_reflections/')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.staffprojectreflection')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StaffTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.stafftask')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'task')},
            },
        ),
    ]
