# Generated by Django 5.1.4 on 2026-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_teacherprofile_is_program_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='response_drawing',
            field=models.ImageField(blank=True, null=True, upload_to='student_drawings/'),
        ),
        migrations.AlterField(
            model_name='activityprompt',
            name='response_type',
            field=models.CharField(choices=[('text', 'Text Response'), ('video', 'Video Response'), ('table', 'Data Table'), ('drawing', 'Drawing Canvas')], default='text', max_length=10),
        ),
    ]
