# Generated by Django 5.1.4 on 2026-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_studentresponse_response_drawing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprompt',
            name='table_row_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
