# Generated by Django 5.1.4 on 2026-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_teachstem_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Email this teacher about new tasks, calendar events and feedback.'),
        ),
    ]
